### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by JoeBengalen** [feryardiant/slim-plates-view#1]
I just read the code a bit an this caught my eye:

https://github.com/feryardiant/slim-plates-view/blob/master/src/Plates.php#L119

Wont that return the return value of `write`? (which is an `int`)

Also, where is this `$container` coming from?
https://github.com/feryardiant/slim-plates-view/blob/master/src/Plates.php#L37
The container should be not be there at all. If you want to register the service in the container use the `PlatesProvider`

**Comment by feryardiant** [comment]
Hi @JoeBengalen 

1. It tested and return `Psr\Http\Message\ResponseInterface` as expected
2. Ah, sorry about that. Previously it's a `PlatesProvider` before I decided to split it into separated classes.

Regards
